version = 1
SPDX-PackageName = "hegemony-step-plugins"
SPDX-PackageSupplier = "Jakub Travnik <jakub.travnik@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/tvarohohlavy/hegemony-step-plugins"

[[annotations]]
path = "uv.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 Jakub Travnik <jakub.travnik@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
